rewrite removePortal as es5 function
Uglifyjs doesn't know anything about es6, so 1.7.0 breaks my build script with error
```
ERROR in index_586f597d6f9d7177eb8b.js from UglifyJs
SyntaxError: Unexpected token punc «(», expected punc «:» [./~/react-modal/lib/components/Modal.js:103,0]
```

fix es6 -> es5